# Generated by Django 4.2.7 on 2023-11-26 00:31

from django.db import migrations, models
import django.utils.timezone
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Post date"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="intro",
            field=models.CharField(max_length=250),
        ),
    ]
